version: "3"

tasks:
  install:
    cmds:
      - helm install {{.CHART}} charts/{{.CHART}} --values tests/{{.CHART}}/{{.VALUES}}
    vars:
      CHART: '{{ (split " " .CLI_ARGS)._0 }}'
      VALUES: '{{ default "values.yaml" (split " " .CLI_ARGS)._1 }}'

  port-forward:
    desc: Forward a service port
    cmds:
      - export POD_NAME=$(kubectl get pods -l "app.kubernetes.io/name={{.CHART}},app.kubernetes.io/instance={{.CHART}}" -o jsonpath="{.items[0].metadata.name}")
      - kubectl port-forward
          $(kubectl get pods -l
            "app.kubernetes.io/name={{.CHART}},app.kubernetes.io/instance={{.CHART}}"
            -o jsonpath="{.items[0].metadata.name}"
          )
        8080:80
      #- kubectl port-forward $POD_NAME 8080:8080
    vars:
      CHART: '{{ (split " " .CLI_ARGS)._0 }}'

  pull-secret:
    desc: Add image pull secret
    cmds:
      - kubectl create secret generic github-pull-secret
          --from-file=.dockerconfigjson=/home/toni/.docker/config.json
          --type=kubernetes.io/dockerconfigjson
