apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tasmo-admin.fullname" . }}
  labels:
    {{- include "tasmo-admin.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tasmo-admin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tasmo-admin.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      {{- if .Values.persistence.existingClaim }}
      - name: tasmoadmin-data
        persistentVolumeClaim:
        {{- with .Values.persistence.existingClaim }}
          claimName: {{ tpl . $ }}
        {{- end }}
      {{- else if not .Values.persistence.storageClassName }}
      - name: tasmoadmin-data
        emptyDir: {}
      {{- end }}
      {{- if and .Values.persistence.storageClassName (not .Values.persistence.existingClaim) }}
      volumeClaimTemplates:
        - metadata:
            name: tasmoadmin-data
            namespace: {{ .Release.Namespace }}
            labels:
              app.kubernetes.io/name: {{ include "tasmoadmin.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/managed-by: {{ .Release.Service }}
          spec:
            {{- if .Values.persistence.storageClassName }}
            storageClassName: {{ .Values.persistence.storageClassName | quote }}
            {{- end }}
            accessModes:
              - {{ .Values.persistence.accessMode | quote }}
            resources:
            requests:
              storage: {{ .Values.persistence.size | quote }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tasmo-admin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: tasmoadmin-data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
