apiVersion: v2
name: tasmo-admin
description: Tasmo Admin for Kubernetes
type: application
version: 1.0.3
appVersion: 1.7.0
icon: https://raw.githubusercontent.com/reloxx13/TasmoAdmin/master/tasmoadmin/resources/img/favicons/favicon-96x96.png
home: https://charts.itstoni.com
keywords:
  - tasmota
  - mqtt
  - eclipse-iot
  - mosquitto
maintainers:
  - name: kilip
    url: https://itstoni.com
